name: Build
on:
  push:
    branches: [main]
    paths-ignore: [README.md]
defaults:
  run:
    shell: bash
env:
jobs:
  win:
    runs-on: windows-2019
    strategy:
      fail-fast: false
      matrix:
        arch: [x64]
    env:
      CLANGVERSION: clang-llvmorg-16-init-907-g8b740747-1
      CRONETVERSION: v106.0.5249.91-2
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.18.1'
      - run: curl -sSL https://commondatastorage.googleapis.com/chromium-browser-clang/Win/$CLANGVERSION.tgz  | tar -xvzf - -C /usr/local
      - run: curl -sSL https://github.com/klzgrad/naiveproxy/releases/download/$CRONETVERSION/cronet-$CRONETVERSION-win-x64.zip -o /tmp/cronet-$CRONETVERSION-win-x64.zip
      - run: unzip /tmp/cronet-$CRONETVERSION-linux-x64.zip -d /usr/local
      - run: GOOS=windows GOARCH=amd64 go build -x -v . -o cro.exe
      - uses: actions/upload-artifact@v2
        with:
          name: cro
          path: cro.exe